[package]
name = "host-rust"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.86"
tokio = { version = "1.38.0", features = ["rt-multi-thread", "macros", "signal", "net", "time"] }
wasmtime = "21.0.1"
wasmtime-wasi = "21.0.1"
