package component:hello;

interface types {
    resource headers {
        get: func(name: string) -> option<string>; 
        set: func(name: string, value: string);
    }

    record error-response {
        status: option<u16>,
        message: string,
    }
}

world example {
    use types.{headers, error-response};

    export request-callback: func(headers: headers) -> result<_, error-response>;
}
