package component:hello;

interface types {
    resource headers {
        get: func(name: string) -> option<string>; 
        set: func(name: string, value: string);
    }
}

world example {
    use types.{headers};

    export request-callback: func(headers: headers) -> result<_, string>;
}
